'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from '@/components/ui/dialog';
import { Loader2, Sparkles, Copy } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { generateCompliantInvoice, type GenerateCompliantInvoiceInput } from '@/ai/flows/generate-compliant-invoice';
import type { Invoice } from '@/lib/types';

interface CompliantInvoiceDialogProps {
  invoice: Invoice;
}

export function CompliantInvoiceDialog({ invoice }: CompliantInvoiceDialogProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [compliantInvoiceText, setCompliantInvoiceText] = useState('');
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsLoading(true);
    setCompliantInvoiceText('');
    try {
      const input: GenerateCompliantInvoiceInput = {
        customerName: invoice.customerName,
        invoiceNumber: invoice.invoiceNumber,
        items: invoice.items.map(item => ({
          description: item.description,
          amount: item.quantity * item.price,
        })),
        totalAmount: invoice.totalAmount,
        date: invoice.invoiceDate.toDate().toLocaleDateString(),
        companyName: 'Invoice Hub',
        companyAddress: '123 Innovation Drive, Tech City, 12345',
        companyContact: 'contact@invoicehub.com',
        legalRequirements: 'Standard US invoice requirements. Include payment terms: Net 30 days.',
      };

      const result = await generateCompliantInvoice(input);
      setCompliantInvoiceText(result.compliantInvoice);
    } catch (error) {
      toast({
        title: 'Generation Failed',
        description: 'Could not generate the compliant invoice.',
        variant: 'destructive',
      });
    }
    setIsLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(compliantInvoiceText);
    toast({ title: 'Copied!', description: 'Invoice text copied to clipboard.' });
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="secondary" onClick={handleGenerate}>
          <Sparkles className="mr-2 h-4 w-4" />
          Generate Compliant Invoice
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle>Legally Compliant Invoice Text</DialogTitle>
          <DialogDescription>
            This invoice text is generated by AI to meet legal standards. Review before sending.
          </DialogDescription>
        </DialogHeader>
        <div className="my-4 max-h-[50vh] overflow-y-auto rounded-md border bg-muted/50 p-4">
          {isLoading ? (
            <div className="flex h-48 items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          ) : (
            <pre className="whitespace-pre-wrap text-sm font-mono">{compliantInvoiceText}</pre>
          )}
        </div>
        <DialogFooter>
            <Button variant="ghost" onClick={() => setIsOpen(false)}>Close</Button>
            <Button onClick={handleCopy} disabled={!compliantInvoiceText || isLoading}>
                <Copy className="mr-2 h-4 w-4" /> Copy Text
            </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
